Add check within report

diff --git a/.github/workflows/redirects_check.yaml b/.github/workflows/redirects_check.yaml
--- a/.github/workflows/redirects_check.yaml
+++ b/.github/workflows/redirects_check.yaml
@@ -46,11 +46,9 @@ jobs:
           if ! [ -z "$var" ];then
             python "scripts/aiven/check_renamed_files.py" --renamed_files ${{ steps.changed-files.outputs.renamed_files }}
           fi
-
-      - name: Check env
-        if: ${{env.MISSING_REDIRECTION}} != ""
-        run: |
-          echo "renamed:"
-          echo ${{env.MISSING_REDIRECTION}}
-          echo "::error::Files were renamed with missing _redirects. Add redirect to renamed files to fix it. \n  ${{env.MISSING_REDIRECTION}}"
-          exit 1
+          if ! [ -z ${{env.MISSING_REDIRECTION}} ];then
+            echo "renamed:"
+            echo ${{env.MISSING_REDIRECTION}}
+            echo "::error::Files were renamed with missing _redirects. Add redirect to renamed files to fix it. \n  ${{env.MISSING_REDIRECTION}}"
+            exit 1
+          fi
